---
all:
  vars:
    ansible_connection_type: ssh
    ansible_user: "{{ ansible_user }}"
    ansible_python_interpreter: /usr/bin/python3.9
  hosts:
    cp1:
      ansible_host: "{{ public_ip['cp1'] }}"
    node1:
      ansible_host: "{{ public_ip['node1'] }}"
    node2:
      ansible_host: "{{ public_ip['node2'] }}"
    gitlab-cicd:
      ansible_host: "{{ public_ip['gitlab-cicd'] }}"  
      ansible_ssh_private_key_file: ~/.ssh/id_rsa  # Явно указать путь к ключу
      ansible_python_interpreter: /usr/bin/python3
      ansible_become: true
      ansible_become_method: sudo
      ansible_become_user: root
  children:
    k8n_cluster:
      hosts:
        cp1:
        node1:
        node2:
    k8n_control_plane:
      hosts:
        cp1:

