apiVersion: apps/v1
kind: Deployment
metadata:
  name: gnn-diploma-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gnn-diploma-app
  template:
    metadata:
      labels:
        app: gnn-diploma-app
    spec:
      containers:
      - name: app
        image: nikogorelov/gnn-diploma-netology:0.0.2  # или конкретный тег, например v1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: gnn-diploma-service
spec:
  selector:
    app: gnn-diploma-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP  # Сделаем NodePort далее









# # k8s/deployment.yaml
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: diploma-webapp
#   namespace: production
# spec:
#   replicas: 2
#   selector:
#     matchLabels:
#       app: diploma-webapp
#   template:
#     metadata:
#       labels:
#         app: diploma-webapp
#     spec:
#       containers:
#       - name: diploma-webapp
#         image: your-registry/diploma-webapp:latest  # ← будет обновляться через kubectl set image
#         ports:
#         - containerPort: 8080
#         resources:
#           limits:
#             memory: "512Mi"
#             cpu: "500m"
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: diploma-webapp-svc
#   namespace: production
# spec:
#   selector:
#     app: diploma-webapp
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 8080
#   type: ClusterIP